# configuracao do bd
# properties é um arquivo de configuração, que vai configurar a aplicação sem mexer no código fonte e cada linha é uma configuração
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=topicos1
quarkus.datasource.password=123456
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/topicos1db

quarkus.hibernate-orm.database.generation=drop-and-create 

quarkus.hibernate-orm.log.sql=true 
quarkus.hibernate-orm.log.bind-parameters=true 

# linha 3 == configurando o banco de dados e dizendo qual banco está usando
# linha 4 == usuário
# linha 5 == senha
# linha 6 == localhost: rodando no próprio computador; 5432: porta do postgres; topicos1db: nome do banco no postgres
# linha 8 == hibernate: tradutor entre o mundo poo e o mundo relacional(banco de dados); nesse comando ele indica como o hibernate deve tratar as tabelas(drop-and-create)
# linha 10 == faz o hibernate mostrar no console as queries SQL
# linha 11 == faz o hibernate mostrar os parâmetros que ele  ta usando também